name: Broken Link Check
on:
  schedule:
    - cron: '* * * * *' # every minute
  repository_dispatch: # run manually
    types: [check-link]
  push:
    branches:
      - feat/broken-link-checker
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        with:
          TARGET: https://supabase.com
          EXCLUDED_KEYWORDS: twitter.com